### ISSUE TITLE
Tip alignment with the data panel

### ISSUE THREAD

**Issue by lm-jkominek** [compgenomicslab/TreeProfiler#39]
Hi, first of all, I absolutely love TreeProfiler - it is a tool I've been looking for in quite some time, and I am super excited to use it. I've been stuck using iTOL for a while, but its rendering faces significant performance troubles with larger trees (anything 1000+), which is something I don't see being an issue with TP. Also, love the internal node data inference, it is fantastic that it can be done automatically or user-provided. Keep up the amazing work :)

Now, onto my actual issue - I'm wondering if it's possible to align the tips of the tree to the data panel, or to the separator between the two, all the while keeping the root of the tree anchored to the left side of the browser? Right now, when I pan around the tree, the tips can get obscured or even disappear entirely under the data panel, especially if there's multiple layouts there. I know we can do horizontal and vertical zoom, but it doesn't quite cut it. 
Now, I also noticed the "adjust position" Advanced option, which does the tip tracking very well, but (A) it only works when I pan around the tree, not when I adjust the separator position to see more data, and (B) the entire tree still moves around, so it's not anchored. What I would envision is basically a horizontal compression of the tree, while keeping the root position and the same taxa visible. While I can imagine this being more difficult to calculate/render while maintaining branch lengths, I would think that the ultrametric/topology-only tree would be much less affected.
 
Thanks in advance, if this was something that could be added to TP!

**Comment by dengzq1234** [comment]
Hi! Thanks for the kind words!

As I quick check, would it be helpful if click the _ultrametric_ option? 
![image](https://github.com/compgenomicslab/TreeProfiler/assets/25636183/55c42913-6a1d-4dbf-90c3-910fca2f7939)

It will give all the tips equidistant to the root, so tips will align with the layouts as shown as the following
![image](https://github.com/compgenomicslab/TreeProfiler/assets/25636183/c010f7dd-b545-4eb7-bb8f-c654c36980c8)

**Comment by lm-jkominek** [comment]
Hi @dengzq1234, ultrametric tree does help a little, but does not solve the problem, because I work with large trees (hundreds/thousands of taxa) so the topology can get quite complicated and doesn't fit on the screen too well. I also have multiple datasets/layouts that I would like to explore, which is why I play with the tree/data panel separator, so that I can visualize both the tree and the data at the same time.

**Comment by dengzq1234** [comment]
I see, it might help you from two side
1) Left side setting activate _ultrametric_ + deactivate _zoom around node_
In the treeview we have a default setting called _zoom around node_ which basically limits the minimum level of zooming horizontally and vertically, by deactivating it you can compact it to smaller scale. 

2) Right side setting (data panel)
with the argument `--column-width` can reduce the size of each column to affort more to see more columns, although sacrificing the visualization

**Comment by lm-jkominek** [comment]
Thank you, appreciate the tips! In the end, I think I will just stick to first panning to cover what I need, and then ALT+scrolling for vertical zoom only.
