### ISSUE TITLE
Hiding the legend

### ISSUE THREAD

**Issue by lm-jkominek** [compgenomicslab/TreeProfiler#40]
When I am loading the examples in my browser via SmartView Tree Explorer, I noticed that there is no option to hide the top-right corner layout legend. Maybe I missed something, but I went through the control panel and couldn't find it anywhere, except for the advanced option to Show/Hide the tree length scale bar/legend? 
Having the option to hide (or collapse) it would come in handy especially with taxonomic data, where the legend becomes very long very fast, and obstructs a significant portion of the screen real estate.

**Comment by dengzq1234** [comment]
Hi! 
Thanks for your message. If layout panel blocked the layouts of tree, hover the mouse to the bottom-right of the panel where you can find a small half-shaded square. When mouse will become up-down arrow as the following figures shows, you can adjust the length of layout panel from maximum 736px(half screen) to mimum 20px, which considers it as collapsing when it block the layouts. For now we don't have the exact option to hide the legend panel completely, we will think about adding minimize option in the panel. Thanks for you suggestion!

![image](https://github.com/compgenomicslab/TreeProfiler/assets/25636183/41fdd45e-4bc9-452c-a975-a399c9914a2b)

![image](https://github.com/compgenomicslab/TreeProfiler/assets/25636183/ebd39595-2f19-45a4-a1f5-3377f8a4ad65)

**Comment by lm-jkominek** [comment]
Thanks a bunch, appreciate it the tip! That should help me for the time being for sure.
