### ISSUE TITLE
Embedding TreeProfiler results

### ISSUE THREAD

**Issue by lm-jkominek** [compgenomicslab/TreeProfiler#41]
Right now when I run `treeprofiler plot` it opens up a new tab in my current browser and serves the results as localhost app. I'm wondering if there is a way/plan to have that accessible perhaps as a JS/React app/widget that could be embedded into other websites? I know that TP uses ETE4's smartview under the hood, so I looked at that repo as well, but couldn't find any information on embedding. Thanks in advance for any tips!

**Comment by dengzq1234** [comment]
At this moment we don't have exact a JS plugin for embeding the viewing session. But in our another tool PhyloCloud(https://phylocloud.cgmlab.org/), which is a web application for tree storing and visualizing, at their we used iframe to host the visualization session 
Example 
https://phylocloud.cgmlab.org/tree_page/61b9bdef3947c122665b8252/

**Comment by lm-jkominek** [comment]
Thanks for letting me know and for the pointer, will look into PhyloCloud!
