### ISSUE TITLE
Inconsistent alignment length in tree legend

### ISSUE THREAD

**Issue by jacgonisa** [compgenomicslab/TreeProfiler#53]
My alignment looks as if it was longer than 2500.

![image](https://github.com/compgenomicslab/TreeProfiler/assets/109277147/50d1797b-d233-4d98-9997-714ee41ec949)

But actually, when checking it manually (word counter) its length is no more than 2100.

**Comment by jacgonisa** [comment]
However, in this case (way smaller tree,with only 13 tips), the total length is 951, which matches the word counter
![image](https://github.com/compgenomicslab/TreeProfiler/assets/109277147/bbbdfcf9-d039-454b-9290-03317dcf4407)

**Comment by dengzq1234** [comment]
Here is the test with longer alignment and seems correct
![image](https://github.com/compgenomicslab/TreeProfiler/assets/25636183/065eef53-aa82-4287-abb3-e4a4a4f99200)
