### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by SchwarzMarek** [compgenomicslab/TreeProfiler#55]
Hi,
after installation for python 3.11

I receive following errors for `treeprofiler annotate` for any test command I try to use.
```
    from ete4.coretype.seqgroup import SeqGroup
ModuleNotFoundError: No module named 'ete4.coretype'
```

I've used the pip installation method (https://github.com/compgenomicslab/TreeProfiler?tab=readme-ov-file#quick-install-via-pip) to fresh `mamba python 3.11` environment.
`pip list` reports 
```
ete3               3.1.3
ete4               4.0.0b2
```
installed, among other packages. 

Re-installation of TreeProfiler from GitHub didn't appear to help.

Could you please suggest working combination of python + ete4 and other packages (with particular versions), I would love to try out this interestingly looking software.
Best
Marek

**Comment by dengzq1234** [comment]
hi @SchwarzMarek, thanks for reminder! I updated the release package to sync with the main branch and now it should work following the documentation!

Best,
Ziqi

**Comment by SchwarzMarek** [comment]
Thanks for the quick update. I'm able to get working installation now.
